export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGOUT = "LOGOUT";

export const SET_ALERT = "SET_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const TRANSFERS_LOADED = "TRANSFERS_LOADED";
export const TRANSFERS_ERROR = "TRANSFERS_ERROR";

export const GET_BANKS_INIT = "GET_BANKS_INIT";
export const GET_BANKS_SUCCESS = "GET_BANKS_SUCCESS";
export const GET_BANKS_ERROR = "GET_BANKS_ERROR";

export const GET_CURRENCIES_INIT = "GET_CURRENCIES_INIT";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_ERROR = "GET_CURRENCIES_ERROR";

export const GET_PENDING_TRANSFERS = "GET_PENDING_TRANSFERS";
export const GET_PENDING_TRANSFERS_ERROR = "GET_PENDING_TRANSFERS_ERROR";

export const GET_TRANSFER = "GET_TRANSFER";
export const GET_TRANSFER_ERROR = "GET_TRANSFER_ERROR";

export const UPDATE_TRANSFER = "UPDATE_TRANSFER";
export const UPDATE_TRANSFER_ERROR = "UPDATE_TRANSFER_ERROR";

export const CCPAYMENTS_LOADED = "CCPAYMENTS_LOADED";
export const CCPAYMENTS_ERROR = "CCPAYMENTS_ERROR";

export const ADD_PAYMENT_BANK = "ADD_PAYMENT_BANK";
export const ADD_PAYMENT_BANK_ERROR = "ADD_PAYMENT_BANK_ERROR";

export const GET_CCPAYMENT = "GET_CCPAYMENT";
export const GET_CCPAYMENT_ERROR = "GET_CCPAYMENT_ERROR";

export const PENDING_ACCPAYMENTS_LOADED = "PENDING_ACCPAYMENTS_LOADED";
export const ACCPAYMENTS_LOADED = "ACCPAYMENTS_LOADED";
export const ACCPAYMENTS_ERROR = "ACCPAYMENTS_ERROR";

export const GET_ACCPAYMENT_DETAILS = "GET_ACCPAYMENT_DETAILS";
export const GET_ACCPAYMENT_DETAILS_ERROR = "GET_ACCPAYMENT_DETAILS_ERROR";

export const GET_PAYMENTS_COUNT = "GET_PAYMENTS_COUNT";
export const GET_PAYMENTS_COUNT_ERROR = "GET_PAYMENTS_COUNT_ERROR";

export const GET_PENDING_PAYMENTS_COUNT = "GET_PENDING_PAYMENTS_COUNT";
export const GET_PENDING_PAYMENTS_COUNT_ERROR = "GET_PENDING_PAYMENTS_COUNT_ERROR";

export const DEBITS_LOADED = "DEBITS_LOADED";
export const DEBITS_ERROR = "DEBITS_ERROR";

export const GET_DEBIT_DETAILS = "GET_DEBIT_DETAILS";
export const GET_DEBIT_DETAILS_ERROR = "GET_DEBIT_DETAILS_ERROR";

export const GET_DEBITS_COUNT = "GET_DEBITS_COUNT";
export const GET_PENDING_DEBITS_COUNT = "GET_PENDING_DEBITS_COUNT";
export const GET_DEBITS_COUNT_ERROR = "GET_DEBITS_COUNT_ERROR";

export const GET_DEBIT_FEES = "GET_DEBIT_FEES";
export const GET_DEBIT_FEES_ERROR = "GET_DEBIT_FEES_ERROR";

export const ADD_DEBIT_BANK = "ADD_DEBIT_BANK";
export const ADD_DEBIT_BANK_ERROR = "ADD_DEBIT_BANK_ERROR";

export const GET_PENDING_DEBITS = "GET_PENDING_DEBITS";
export const GET_PENDING_DEBITS_ERROR = "GET_PENDING_DEBITS_ERROR";

export const GET_USERS = "GET_USERS";
export const GETUSERS_ERROR = "GETUSERS_ERROR";
export const GET_SUBSCRIBERS = "GET_SUBSCRIBERS";
export const GETSUBSCRIBERS_ERROR = "GETSUBSCRIBERS_ERROR";

export const ADD_USER = "ADD_USER";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const PROFILE_DATA = "PROFILE_DATA";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const GETSUPPLIERS_ERROR = "GETSUPPLIERS_ERROR";
export const GET_SUPPLIER_PROFILE = "GET_SUPPLIER_PROFILE";
export const SUPPLIER_PROFILE_ERROR = "SUPPLIER_PROFILE_ERROR";

export const ADD_SUPPLIER_ACCOUNT = "ADD_SUPPLIER_ACCOUNT";
export const ADD_SUPPLIER_ACCOUNT_ERROR = "ADD_SUPPLIER_ACCOUNT_ERROR";

export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const DELETE_SUPPLIER_ERROR = "DELETE_SUPPLIER_ERROR";

export const GET_PRODUCTS_INIT = "GET_PRODUCTS_INIT";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_PRODUCT_DATA_INIT = "GET_PRODUCT_DATA_INIT";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_ERROR = "GET_PRODUCT_DATA_ERROR";

export const ADD_PRODUCT_INIT = "ADD_PRODUCT_INIT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const EDIT_PRODUCT_INIT = "EDIT_PRODUCT_INIT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const DELETE_PRODUCT_INIT = "DELETE_PRODUCT_INIT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const GET_BANK_PAYMENTS = "GET_BANK_PAYMENTS";
export const GET_BANK_PAYMENTS_ERROR = "GET_BANK_PAYMENTS_ERROR";
