export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGOUT = "LOGOUT";

export const SET_ALERT = "SET_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const TRANSFERS_LOADED = "TRANSFERS_LOADED";
export const TRANSFERS_ERROR = "TRANSFERS_ERROR";

export const GET_BANKS_INIT = "GET_BANKS_INIT";
export const GET_BANKS_SUCCESS = "GET_BANKS_SUCCESS";
export const GET_BANKS_ERROR = "GET_BANKS_ERROR";

export const GET_CURRENCIES_INIT = "GET_CURRENCIES_INIT";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";

export const GET_CURRENCY_INIT = "GET_CURRENCY_INIT";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";

export const EDIT_CURRENCY_INIT = "EDIT_CURRENCY_INIT";
export const EDIT_CURRENCY_SUCCESS = "EDIT_CURRENCY_SUCCESS";

export const CURRENCY_ERROR = "CURRENCY_ERROR";

export const GET_PENDING_TRANSFERS = "GET_PENDING_TRANSFERS";
export const GET_PENDING_TRANSFERS_ERROR = "GET_PENDING_TRANSFERS_ERROR";

export const GET_TRANSFER = "GET_TRANSFER";
export const GET_TRANSFER_ERROR = "GET_TRANSFER_ERROR";

export const UPDATE_TRANSFER = "UPDATE_TRANSFER";
export const UPDATE_TRANSFER_ERROR = "UPDATE_TRANSFER_ERROR";

export const GET_PAYMENTS_INIT = "GET_PAYMENTS_INIT";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";

export const GET_PAYMENT_DETAILS_INIT = "GET_PAYMENT_DETAILS_INIT";
export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS";

export const PROCESS_PAYMENT_INIT = "PROCESS_PAYMENT_INIT";
export const PROCESS_PAYMENT_SUCCESS = "PROCESS_PAYMENT_SUCCESS";

export const PROCESS_BULK_PAYMENTS_INIT = "PROCESS_BULK_PAYMENTS_INIT";
export const PROCESS_BULK_PAYMENTS_SUCCESS = "PROCESS_BULK_PAYMENTS_SUCCESS";

export const CANCEL_PAYMENT_INIT = "CANCEL_PAYMENT_INIT";
export const CANCEL_PAYMENT_SUCCESS = "CANCEL_PAYMENT_SUCCESS";

export const PAYMENTS_ERROR = "PAYMENTS_ERROR";
export const CLEAR_PAYMENTS_ERROR = "CLEAR_PAYMENTS_ERROR";

export const GET_PAYMENTS_COUNT = "GET_PAYMENTS_COUNT";
export const GET_PAYMENTS_COUNT_ERROR = "GET_PAYMENTS_COUNT_ERROR";

export const GET_PENDING_PAYMENTS_COUNT = "GET_PENDING_PAYMENTS_COUNT";
export const GET_PENDING_PAYMENTS_COUNT_ERROR = "GET_PENDING_PAYMENTS_COUNT_ERROR";

export const GET_DEBITS_INIT = "GET_DEBITS_INIT";
export const GET_DEBITS_SUCCESS = "GET_DEBITS_SUCCESS";

export const GET_DEBIT_DETAILS_INIT = "GET_DEBIT_DETAILS_INIT";
export const GET_DEBIT_DETAILS_SUCCESS = "GET_DEBIT_DETAILS_SUCCESS";

export const GET_DEBIT_FEES_INIT = "GET_DEBIT_FEES_INIT";
export const GET_DEBIT_FEES_SUCCESS = "GET_DEBIT_FEES_SUCCESS";

export const PROCESS_DEBIT_FEE_INIT = "PROCESS_DEBIT_FEE_INIT";
export const PROCESS_DEBIT_FEE_SUCCESS = "PROCESS_DEBIT_FEE_SUCCESS";

export const PROCESS_BULK_DEBITS_INIT = "PROCESS_BULK_DEBITS_INIT";
export const PROCESS_BULK_DEBITS_SUCCESS = "PROCESS_BULK_DEBITS_SUCCESS";

export const CANCEL_DEBIT_INIT = "CANCEL_DEBIT_INIT";
export const CANCEL_DEBIT_SUCCESS = "CANCEL_DEBIT_SUCCESS";

export const DEBITS_ERROR = "DEBITS_ERROR";
export const CLEAR_DEBITS_ERROR = "CLEAR_DEBITS_ERROR";

export const GET_USERS = "GET_USERS";
export const GETUSERS_ERROR = "GETUSERS_ERROR";
export const GET_SUBSCRIBERS = "GET_SUBSCRIBERS";
export const GETSUBSCRIBERS_ERROR = "GETSUBSCRIBERS_ERROR";

export const ADD_USER = "ADD_USER";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const PROFILE_DATA = "PROFILE_DATA";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const GET_SUPPLIERS_INIT = "GET_SUPPLIERS_INIT";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";
export const GET_SUPPLIERS_ERROR = "GET_SUPPLIERS_ERROR";

export const GET_SUPPLIER_PROFILE_INIT = "GET_SUPPLIER_PROFILE_INIT";
export const GET_SUPPLIER_PROFILE_SUCCESS = "GET_SUPPLIER_PROFILE_SUCCESS";
export const GET_SUPPLIER_PROFILE_ERROR = "GET_SUPPLIER_PROFILE_ERROR";

export const ADD_SUPPLIER_INIT = "ADD_SUPPLIER_INIT";
export const ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";

export const EDIT_SUPPLIER_INIT = "EDIT_SUPPLIER_INIT";
export const EDIT_SUPPLIER_SUCCESS = "EDIT_SUPPLIER_SUCCESS";

export const DELETE_SUPPLIER_INIT = "DELETE_SUPPLIER_INIT";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";

export const SUPPLIER_ERROR = "SUPPLIER_ERROR";

export const ADD_SUPPLIER_ACCOUNT_INIT = "ADD_SUPPLIER_ACCOUNT_INIT";
export const ADD_SUPPLIER_ACCOUNT_SUCCESS = "ADD_SUPPLIER_ACCOUNT_SUCCESS";
export const ADD_SUPPLIER_ACCOUNT_ERROR = "ADD_SUPPLIER_ACCOUNT_ERROR";

export const GET_SUPPLIER_ACCOUNT_INIT = "GET_SUPPLIER_ACCOUNT_INIT";
export const GET_SUPPLIER_ACCOUNT_SUCCESS = "GET_SUPPLIER_ACCOUNT_SUCCESS";
export const GET_SUPPLIER_ACCOUNT_ERROR = "GET_SUPPLIER_ACCOUNT_ERROR";

export const GET_PRODUCTS_INIT = "GET_PRODUCTS_INIT";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_SUPPLIER_PRODUCTS_INIT = "GET_SUPPLIER_PRODUCTS_INIT";
export const GET_SUPPLIER_PRODUCTS_SUCCESS = "GET_SUPPLIER_PRODUCTS_SUCCESS";
export const GET_SUPPLIER_PRODUCTS_ERROR = "GET_SUPPLIER_PRODUCTS_ERROR";

export const GET_PRODUCT_DATA_INIT = "GET_PRODUCT_DATA_INIT";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_ERROR = "GET_PRODUCT_DATA_ERROR";

export const ADD_PRODUCT_INIT = "ADD_PRODUCT_INIT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const EDIT_PRODUCT_INIT = "EDIT_PRODUCT_INIT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const DELETE_PRODUCT_INIT = "DELETE_PRODUCT_INIT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const GET_BANK_PAYMENTS = "GET_BANK_PAYMENTS";
export const GET_BANK_PAYMENTS_ERROR = "GET_BANK_PAYMENTS_ERROR";
